### GET RANDOM TRIVIA QUESTION

@baseUrl = https://opentdb.com/api.php?

GET https://opentdb.com/api.php?amount=10&type=multiple

# SPORT

# EASY
###
GET {{baseUrl}}amount=1&category=21&difficulty=easy&type=multiple&encode=base64

###
GET {{baseUrl}}amount=1&category=21&difficulty=easy&type=multiple

# MEDIUM
###
GET {{baseUrl}}amount=1&category=21&difficulty=medium&type=multiple&encode=base64

###
GET {{baseUrl}}amount=1&category=21&difficulty=medium&type=multiple


# HARD
###
GET {{baseUrl}}amount=1&category=21&difficulty=hard&type=multiple&encode=base64

###
GET {{baseUrl}}amount=1&category=21&difficulty=hard&type=multiple

#GENERAL KNOWLEDGE

#EASY
###
###
###

GET {{baseUrl}}amount=1&category=9&difficulty=easy&type=multiple

###

GET {{baseUrl}}amount=1&category=9&difficulty=medium&type=multiple

###

GET {{baseUrl}}amount=1&category=9&difficulty=hard&type=multiple

###

#FILMS

GET {{baseUrl}}amount=1&category=11&difficulty=easy&type=multiple

###

GET {{baseUrl}}amount=1&category=11&difficulty=easy&type=multiple


###

GET {{baseUrl}}amount=1&category=11&difficulty=hard&type=multiple